### PR TITLE
fix: Correctly handle unicode in windows paths

### LINKED ISSUE #251: [crash] if database path exist space or cyrillic symbols
file sentry_path_windows.c
line 53

use method _wopen

return -1 and run settup to null
sentry_init return 0
and i call any sentry_set_extra i get crash

### PR DESCRIPTION
**Pull request by Swatinem**
fixes #251

### CODE REVIEW

**Comment by jan-auer** [comment]
@Swatinem I'd leave #251 open though, since `sentry_set_extra` still shouldn't crash the app if initialization fails for whatever reason. Could we harden this?

File: include/sentry.h [hunk 1]
```diff
@@ -4,7 +4,16 @@
  * sentry-native is a C client to send events to native from
  * C and C++ applications.  It can work together with breakpad/crashpad
  * but also send events on its own.
+ *
+ * NOTE on encodings:
+ *
+ * Sentry will assume an encoding of UTF-8 for all string data that is captured
+ * and being sent to sentry as an Event.
+ * All the functions that are dealing with *paths* will assume an OS-specific
+ * encoding, typically ANSI on Windows, and UTF-8 on Unix; and they provide
```
Comment (mitsuhiko) [inline include/sentry.h:13]:
```suggestion
 * encoding, typically ANSI on Windows, UTF-8 on macOS; and the local encoding on Linux and they provide
```
