### PR TITLE
tests: Refactor tests and fix minor issues

### LINKED ISSUE #138: CJK character encoding issue on Windows
I found CJK characters does not handle correctly on Windows.

- Tested Environment: Windows x64 10.0.19041.21
- Tested SDK version: Sentry Native 0.1.4
- Tested IDE: Visual Studio 15.9.19
- Tested Visual C++ Compiler Version: 19.16.27035

Sample Code:
```cpp
	std::string str = std::wstring_convert<std::codecvt_utf8<wchar_t>, wchar_t>{}.to_bytes(L"한글 테스트");
	sentry_value_t event = sentry_value_new_event();
	sentry_value_set_by_key(event, "message",
		sentry_value_new_string(str.c_str()));
	sentry_capture_event(event);
```

Result:
image

I'm suspecting this issue because of the below code.
https://github.com/getsentry/sentry-native/blob/master/src/json.hpp#L117

### PR DESCRIPTION
**Pull request by Swatinem**
* Move integration tests to use the example
* Proper json serialization of unicode: fixes #138
* Use an explicit `values` key for thread stacktrace
* Move `ldd` test from azure into pytest

### CODE REVIEW

File: src/sentry_json.c [hunk 1]
```diff
@@ -131,9 +132,12 @@ write_json_str(sentry_jsonwriter_t *jw, const char *str)
             write_str(jw, "\\t");
             break;
         default:
+            // See https://tools.ietf.org/html/rfc8259#section-7
+            // We only need to escape the control characters, otherwise we
+            // assume that `str` is valid utf-8
             if (*ptr < 32) {
                 char buf[10];
-                snprintf(buf, sizeof(buf), "u%04x", *ptr);
+                snprintf(buf, sizeof(buf), "\\u%04x", *ptr);
```
Comment (jan-auer) [inline src/sentry_json.c]: oh my god.
