### PR TITLE
fix(win): make narrow utf-8 the canoncial path encoding

### LINKED ISSUE #1397: Use narrow UTF-8 as the canonical encoding for paths on Windows
The Native SDK uses narrow UTF-8 encoding throughout the code base as the canonical string encoding. 

The only exception to this rule is the strings representing paths on Windows, which use wide characters that depend on the system or application code page settings when they reach our output boundary (i.e., when writing to files or the console). The reason for handling Windows paths separately was that Win32 APIs exclusively use this encoding. 

By making wide chars the canonical path encoding on Windows, we can prevent conversions back and forth. However, to make this work, we have to rely on using `%ls` or `%S` format specifiers wherever we reach an output boundary, and those require CRT locale configuration or console code-page configuration on the application side (to match the system settings) in order not to get encoding errors when using non-ASCII characters in paths.

This became evident in a recent issue (#1388), which, at its core, was about a different topic related to path encoding on Windows, but also showed that our _logging_ fails to render paths correctly if those paths contain Cyrillic characters, if applications do not maintain correct locale and console code-page settings. The problem, however, is worse than just logging, because we use the same mechanism for serialization.

Let's make narrow UTF-8 the canonical encoding on Windows too, to eliminate any platform-specific issues in the output. This would mean to

* eliminate all uses of `%S`/`%ls` format specifiers in the code base
* using a UTF-8 `char*` as the internal path representation, like we do on all other platforms
* introduce wide-char conversion where it is necessary at the boundary
* provide a cached accessor for the Windows code base so that we do not have to convert back to wide char on every Win32 or public interface boundary

### LINKED ISSUE #1410: Crash on initialization when database path is too long (breakpad)
**Description**

This issue was originally reported for Unreal SDK:
- https://github.com/getsentry/sentry-unreal/issues/1111

Customer integrated FAB version of the plugin (`0.21.1`) which uses `sentry-native` with `breakpad` internally on Windows. When the game build is placed in a directory with a long path a crash occurs during SDK initialization. This behavior is likely caused by a buffer overflow (`MAX_PATH` is 260) in this section of [breakpad’s code](https://github.com/getsentry/breakpad/blob/9b606719129be728005e3c295d4c74bd1a15c0ed/src/client/windows/handler/exception_handler.cc#L1054-L1056)

While the latest Unreal plugin version now uses only `Crashpad` on Windows, `Breakpad` is still used on Xbox where this could potentially become a problem in the future.

**When does the problem happen**

- [ ] During build
- [x] During run-time
- [ ] When capturing a hard crash

**Environment**

- OS: Windows
- Native SDK 0.7.16
- SENTRY_BACKEND=breakpad

**Steps To Reproduce**

1. Use long string to configure database path via `sentry_options_set_database_path`, e.g:
```
D:\twin_apps\applications\qa\d82f49c8-42fe-4e64-b962-09965c408faa\f92d3ddd-10ca-4f73-a9e1-6f551cde3ed8\00e4764d-67cb-4f5e-8562-814a4cf2ddd2\333e32d1-7de2-47b0-82af-7724af5ba27a\bin\Windows\TestLongPath\.sentry-native
```
2. Call `sentry-init`

Expected result:
- SDK initializes successfully.

Actual result:
- SDK crashes with the following output:

```
2025.10.10-07.20.54:340][  0]LogSentrySdk: Sentry plugin auto initialization: true
[2025.10.10-07.20.54:341][  0]LogSentrySdk: using database path "D:\twin_apps\applications\qa\d82f49c8-42fe-4e64-b962-09965c408faa\f92d3ddd-10ca-4f73-a9e1-6f551cde3ed8\00e4764d-67cb-4f5e-8562-814a4cf2ddd2\333e32d1-7de2-47b0-82af-7724af5ba27a\bin\Windows\TestLongPath\.sentry-native"
[2025.10.10-07.20.54:341][  0]LogSentrySdk: Verbose: starting transport
[2025.10.10-07.20.54:343][  0]LogSentrySdk: Verbose: starting background worker thread
[2025.10.10-07.20.54:343][  0]LogSentrySdk: Verbose: starting backend
[2025.10.10-07.20.54:343][  0]LogSentrySdk: Verbose: background worker thread started
[2025.10.10-07.20.54:343][  0]LogWindows: Error: appError called: Fatal error: [File:D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp] [Line: 72] 
SECURE CRT: Invalid parameter detected.
Expression: Unknown Function: Unknown. File: Unknown Line: 0

[2025.10.10-07.20.54:343][  0]LogWindows: Windows GetLastError: The operation completed successfully. (0)
[2025.10.10-07.21.05:976][  0]LogWindows: Could not start crash report client using ../../../Engine/Binaries/Win64/CrashReportClient-Win64-Debug.exe
[2025.10.10-07.21.05:977][  0]LogMemory: Platform Memory Stats for Windows
[2025.10.10-07.21.05:977][  0]LogMemory: Process Physical Memory: 576.44 MB used, 601.59 MB peak
[2025.10.10-07.21.05:977][  0]LogMemory: Process Virtual Memory: 741.76 MB used, 767.84 MB peak
[2025.10.10-07.21.05:977][  0]LogMemory: Physical Memory: 28283.82 MB used,  36960.46 MB free, 65244.29 MB total
[2025.10.10-07.21.05:977][  0]LogMemory: Virtual Memory: 39435.75 MB used,  40144.54 MB free, 79580.28 MB total
[2025.10.10-07.21.05:977][  0]Message dialog closed, result: Ok, title: The UE-TestLongPath Game has crashed and will close, text: Fatal error: [File:D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp] [Line: 72] 
SECURE CRT: Invalid parameter detected.
Expression: Unknown Function: Unknown. File: Unknown Line: 0

[2025.10.10-07.21.05:977][  0]LogWindows: Error: === Critical error: ===
[2025.10.10-07.21.05:977][  0]LogWindows: Error: 
[2025.10.10-07.21.05:977][  0]LogWindows: Error: Fatal error: [File:D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp] [Line: 72] 
[2025.10.10-07.21.05:977][  0]LogWindows: Error: SECURE CRT: Invalid parameter detected.
[2025.10.10-07.21.05:977][  0]LogWindows: Error: Expression: Unknown Function: Unknown. File: Unknown Line: 0
[2025.10.10-07.21.05:977][  0]LogWindows: Error: 
[2025.10.10-07.21.05:977][  0]LogWindows: Error: 
[2025.10.10-07.21.05:977][  0]LogWindows: Error: 
[2025.10.10-07.21.05:977][  0]LogWindows: Error: [Callstack] 0x00007ff762427ab9 TestLongPath.exe!InvalidParameterHandler() []
[2025.10.10-07.21.05:977][  0]LogWindows: Error: [Callstack] 0x00007ffa1091de76 ucrtbase.dll!UnknownFunction []
[2025.10.10-07.21.05:977][  0]LogWindows: Error: [Callstack] 0x00007ffa109203ec ucrtbase.dll!UnknownFunction []
[2025.10.10-07.21.05:977][  0]LogWindows: Error: [Callstack] 0x00007ff765908c85 TestLongPath.exe!swprintf_s() []
[2025.10.10-07.21.05:977][  0]LogWindows: Error: [Callstack] 0x00007ff765908341 TestLongPath.exe!google_breakpad::ExceptionHandler::UpdateNextID() []
[2025.10.10-07.21.05:977][  0]LogWindows: Error: [Callstack] 0x00007ff765907efb TestLongPath.exe!google_breakpad::ExceptionHandler::Initialize() []
[2025.10.10-07.21.05:977][  0]LogWindows: Error: [Callstack] 0x00007ff765906f30 TestLongPath.exe!google_breakpad::ExceptionHandler::ExceptionHandler() []
[2025.10.10-07.21.05:977][  0]LogWindows: Error: [Callstack] 0x00007ff765903674 TestLongPath.exe!sentry__backend_free() []
[2025.10.10-07.21.05:977][  0]LogWindows: Error: [Callstack] 0x00007ff7658f264a TestLongPath.exe!sentry_init() []
[2025.10.10-07.21.05:977][  0]LogWindows: Error: [Callstack] 0x00007ff762453525 TestLongPath.exe!SentrySubsystemDesktop::InitWithSettings() [C:\Users\tusta\Desktop\TestLongPath\Plugins\Sentry_5.3_FAB\Source\Sentry\Private\Desktop\SentrySubsystemDesktop.cpp:280]
[2025.10.10-07.21.05:977][  0]LogWindows: Error: [Callstack] 0x00007ff762470db5 TestLongPath.exe!USentrySubsystem::Initialize() [C:\Users\tusta\Desktop\TestLongPath\Plugins\Sentry_5.3_FAB\Source\Sentry\Private\SentrySubsystem.cpp:118]
[2025.10.10-07.21.05:977][  0]LogWindows: Error: [Callstack] 0x00007ff762471225 TestLongPath.exe!USentrySubsystem::Initialize() [C:\Users\tusta\Desktop\TestLongPath\Plugins\Sentry_5.3_FAB\Source\Sentry\Private\SentrySubsystem.cpp:59]
[2025.10.10-07.21.05:977][  0]LogWindows: Error: [Callstack] 0x00007ff761afc3a9 TestLongPath.exe!FSubsystemCollectionBase::AddAndInitializeSubsystem() []
[2025.10.10-07.21.05:977][  0]LogWindows: Error: [Callstack] 0x00007ff761b3269e TestLongPath.exe!FSubsystemCollectionBase::Initialize() []
[2025.10.10-07.21.05:977][  0]LogWindows: Error: [Callstack] 0x00007ff761c2380a TestLongPath.exe!UEngine::Init() []
[2025.10.10-07.21.05:977][  0]LogWindows: Error: [Callstack] 0x00007ff760e14b35 TestLongPath.exe!UGameEngine::Init() []
[2025.10.10-07.21.05:977][  0]LogWindows: Error: [Callstack] 0x00007ff76240a688 TestLongPath.exe!FEngineLoop::Init() []
[2025.10.10-07.21.05:977][  0]LogWindows: Error: [Callstack] 0x00007ff7624274a6 TestLongPath.exe!GuardedMain() []
[2025.10.10-07.21.05:977][  0]LogWindows: Error: [Callstack] 0x00007ff76242769a TestLongPath.exe!GuardedMainWrapper() []
[2025.10.10-07.21.05:977][  0]LogWindows: Error: [Callstack] 0x00007ff76242a546 TestLongPath.exe!LaunchWindowsStartup() []
[2025.10.10-07.21.05:977][  0]LogWindows: Error: [Callstack] 0x00007ff76243a134 TestLongPath.exe!WinMain() []
[2025.10.10-07.21.05:977][  0]LogWindows: Error: [Callstack] 0x00007ff765a461fa TestLongPath.exe!__scrt_common_main_seh() [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
[2025.10.10-07.21.05:977][  0]LogWindows: Error: [Callstack] 0x00007ffa10fbe8d7 KERNEL32.DLL!UnknownFunction []
[2025.10.10-07.21.05:977][  0]LogWindows: Error: 
[2025.10.10-07.21.05:979][  0]LogExit: Executing StaticShutdownAfterError
[2025.10.10-07.21.05:979][  0]LogWindows: FPlatformMisc::RequestExit(1, LaunchWindowsStartup.ExceptionHandler)
[2025.10.10-07.21.05:979][  0]LogWindows: FPlatformMisc::RequestExitWithStatus(1, 3, LaunchWindowsStartup.ExceptionHandler)
[2025.10.10-07.21.05:979][  0]LogCore: Engine exit requested (reason: Win RequestExit)
```

### PR DESCRIPTION
**Pull request by supervacuus**
Fixes #1397 (which also contains an explanation of the approach followed in this PR).

Fixes #1410.

### CODE REVIEW

File: src/sentry_path.h [hunk 1]
```diff
@@ -2,20 +2,15 @@
...
 
+struct sentry_path_s {
+    char *path;
 #ifdef SENTRY_PLATFORM_WINDOWS
-typedef wchar_t sentry_pathchar_t;
-#    define SENTRY_PATH_PRI "S"
-#else
-typedef char sentry_pathchar_t;
-#    define SENTRY_PATH_PRI "s"
+    wchar_t *path_w;
```
Comment (JoshuaMoelans) [inline src/sentry_path.h:12]: Should we have some unit tests that verify this value is correctly stored?

e.g. before we had 
`TEST_CHECK(_wcsicmp(path->path, L"foo/bar/baz.txt") == 0);`

Which was now replaced by
`TEST_CHECK(_stricmp(path->path, "foo/bar/baz.txt") == 0);`

But shouldn't we also check that
`TEST_CHECK(_wcsicmp(path->path_w, L"foo/bar/baz.txt") == 0);`

File: tests/unit/test_fuzzfailures.c [hunk 2]
```diff
@@ -8,7 +8,7 @@
 static void
 parse_json_roundtrip(const sentry_path_t *path)
 {
-    // printf("Running %" SENTRY_PATH_PRI "\n", path->path);
+    // printf("Running %s\n", path->path);
```
Comment (JoshuaMoelans) [inline tests/unit/test_fuzzfailures.c]: This was already commented out, so I think we can remove it
```suggestion
```

File: src/sentry_path.h
Comment (JoshuaMoelans) [inline src/sentry_path.h:53]: With the changes made, the functions now assume UTF-8 for all platforms right?

File: src/sentry_string.c
Comment (JoshuaMoelans) [inline src/sentry_string.c]: Doing the length check probably also makes sense here inside `sentry__string_from_wstr` (not sure the GitHub UI shows the correct suggestion location)

```suggestion
int len = WideCharToMultiByte(CP_UTF8, 0, s, -1, NULL, 0, NULL, NULL);
if (len <= 0) {
    return NULL;
}

char *rv = sentry_malloc((size_t)len);
```

File: src/path/sentry_path_windows.c [hunk 3]
```diff
@@ -143,11 +198,27 @@ sentry__path_from_wstr_n(const wchar_t *s, size_t s_len)
...
     }
-    sentry_path_t *rv = path_with_len(s_len + 1);
-    if (rv) {
-        memcpy(rv->path, s, s_len * sizeof(wchar_t));
-        rv->path[s_len] = 0;
+
+    sentry_path_t *rv = SENTRY_MAKE(sentry_path_t);
+    if (!rv) {
+        return rv;
     }
```
Comment (JoshuaMoelans) [inline src/path/sentry_path_windows.c:215]: We could be more consistent with the other 'failing' return paths here

```suggestion
    sentry_path_t *rv = SENTRY_MAKE(sentry_path_t);
    if (!rv) {
        return NULL;
}
```

File: src/path/sentry_path_windows.c [hunk 4]
```diff
@@ -80,43 +85,90 @@ sentry__filelock_unlock(sentry_filelock_t *lock)
...
     if (!len) {
         SENTRY_WARN("unable to get current exe path");
-        sentry__path_free(path);
+        sentry_free(path_wstr);
         return NULL;
     }
+    sentry_path_t *path = SENTRY_MAKE(sentry_path_t);
+    if (!path) {
+        sentry_free(path_wstr);
+        return path;
```
Comment (JoshuaMoelans) [inline src/path/sentry_path_windows.c]: We could be more consistent with the other 'failing' return paths here (inside `if(!path)`)

```suggestion
        return NULL;
```

**Review by JoshuaMoelans — COMMENTED** [review]
This looks pretty good on a first viewing. A few minor comments about some cleanup & clarification.

File: src/sentry_path.h (hunk 1 above)
Comment (supervacuus) [reply src/sentry_path.h:12]: Yeah, I adapted the changes to the unit test during the first iteration, and I initially planned to make the cache lazy. But given that the current implementation eagerly initializes the wide string, we can assume it is set (at least when any module-level initializer is used).

File: src/sentry_path.h
Comment (supervacuus) [reply src/sentry_path.h:53]: Yes!

File: include/sentry.h [hunk 5]
```diff
@@ -10,14 +10,35 @@
...
+ * opaque. On Windows, the situation is much more complex. This is because
+ * Windows has
+ * - locale-dependent multibyte encoding in the CRT,
+ * - ANSI codepage-dependent multibyte encoding in the console and against the
+ *   A-functions of the Win32 API,
+ * - which can be configured independently by the application but also on the
+ *   system level.
+ * The above makes it very hard for us to track which kind of encoding to
+ * expect (and often it isn't clear to the application developer either).
+ * Moreover, in contrast to the UINXes at certain points we have to make the
```
Comment (JoshuaMoelans) [inline include/sentry.h]: (nit:typo)
```suggestion
 * Moreover, in contrast to the UNIXes at certain points we have to make the
```

File: include/sentry.h [hunk 6]
```diff
@@ -532,9 +553,9 @@ SENTRY_EXPERIMENTAL_API sentry_value_t sentry_value_new_stacktrace(
 /**
  * Sets the Stack Trace conforming to the Stack Trace Interface in a value.
  *
- * The value argument must be either an exception or thread object.
+ * The value argument must be either an exception or a thread object.
  *
- * If `ips` is NULL the current stack trace is captured, otherwise `len` stack
+ * If `ips` is NULL, the current stack trace is captured, otherwise `len` stack
```
Comment (JoshuaMoelans) [inline include/sentry.h]: (nit: consistency with change above)
```suggestion
 * If `ips` is NULL, the current stack trace is captured. Otherwise, `len` stack
```

File: src/path/sentry_path_windows.c [hunk 7]
```diff
@@ -375,23 +375,26 @@ sentry__path_get_mtime(const sentry_path_t *path)
...
         return NULL;
     }
 
     // concat into a new path
-    size_t len_base = strlen(base->path);
-    size_t len_suffix = strlen(suffix_path->path);
-    size_t len = len_base + len_suffix + 1;
+    const size_t len_base = strlen(base->path);
+    const size_t len_suffix = strlen(suffix_path->path);
+    const size_t len = len_base + len_suffix + 1;
```
Comment (JoshuaMoelans) [inline src/path/sentry_path_windows.c:394]: (I created a PR for these https://github.com/getsentry/sentry-native/pull/1422)

For completeness sake, there are a few more `size_t` values that could be `const`'d

https://github.com/getsentry/sentry-native/blob/ref/win/make_path_narrow_utf8_on_windows/src/path/sentry_path_windows.c#L311-L312
https://github.com/getsentry/sentry-native/blob/ref/win/make_path_narrow_utf8_on_windows/src/path/sentry_path_windows.c#L415
https://github.com/getsentry/sentry-native/blob/ref/win/make_path_narrow_utf8_on_windows/src/path/sentry_path_windows.c#L438-L439
https://github.com/getsentry/sentry-native/blob/ref/win/make_path_narrow_utf8_on_windows/src/path/sentry_path_windows.c#L528

File: src/sentry_string.c [hunk 8]
```diff
@@ -119,19 +127,39 @@ sentry__string_from_wstr_n(const wchar_t *s, size_t s_len)
...
     return rv;
 }
+
+wchar_t *
+sentry__string_clone_wstr(const wchar_t *str)
+{
+    if (!str) {
+        return NULL;
+    }
+    size_t str_len = wcslen(str);
```
Comment (JoshuaMoelans) [inline src/sentry_string.c]: (Also part of the PR https://github.com/getsentry/sentry-native/pull/1422)

(nit) some more const
```suggestion
    const size_t str_len = wcslen(str);
```

File: src/path/sentry_path_windows.c [hunk 9]
```diff
@@ -80,43 +86,91 @@ sentry__filelock_unlock(sentry_filelock_t *lock)
...
+    }
+    // we convert the wide-string absolute path back to canonical narrow UTF-8
+    // and use the returned and allocate full as our wide string cache.
+    rv->path = sentry__string_from_wstr(full);
+    if (!rv->path) {
+        sentry_free(full);
+        sentry_free(rv);
+        return NULL;
+    }
+    rv->path_w = full;
```
[the remark this answers is not in the document]
Comment (supervacuus) [reply src/path/sentry_path_windows.c]: The comment right above its usage raises exactly this point, but thanks for the chat. `sentry_malloc` uses `malloc` on Windows, so there is no allocator mismatch or undefined behavior. However, there could be down the road if allocators become configurable, which is exactly what the comment mentions. In that case, the entire code base would need to be inspected for functions that allocate without "our" allocator, and most won't have a comment.
